# Generated by Django 5.0.4 on 2024-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('insight', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('pestle', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('likelihood', models.IntegerField()),
                ('relevance', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('published', models.DateTimeField(blank=True)),
                ('added', models.DateTimeField(blank=True)),
            ],
        ),
    ]
